POST http://localhost:8080/makeArticle
Content-Type: application/json

{
  "title": "hello for test",
  "content": "test for content",
  "keyword": "#test"
}

> {%
    client.global.set("articleId", response.body);
    console.log(client.global.get("articleId"));
%}

###
GET http://localhost:8080/likeArticle?articleId={{articleId}}

###
GET http://localhost:8080/getTrendingArticles

> {% client.log("trendingArticles: ", response.body) %}

###
POST http://localhost:8080/problemSolving
Content-Type: application/json

{
  "userId": 123,
  "problemId": 123,
  "solved": 1
}